server:
  port: 38081
dubbo:
  application:
    name: dubbo-provider-demo
  registry:
    protocol: zookeeper
    address: xxxx:52181
    client: zkclient
  protocol:
    name: dubbo
    port: 20882
    payload: 2147483647
  provider:
    timeout: 60000